apiVersion: v1
data:
    password: ENC[AES256_GCM,data:txixtZcnm2r9h8PJqT1RyAXNoHRJtMP4gzW3Qd5shIRYn/J9Vft8/c+t5l6i5NKiciPxl3OaHthGSmWotG13fkbM7kRH2cC1hvdVVK9aL29PdwJkAAZa4w==,iv:AZmfXB6V91t2QxAmfSuEfE7hWi/jDze6Zu2jt9TyN1A=,tag:8AP6WQtjVrPOS6OGaNtnmw==,type:str]
kind: Secret
metadata:
    name: redis-auth
    namespace: takovibe
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2J5bytqNnk0eU5TZWE3
            Rm5aeXRJdW0zZk9CVzJhckpudzNYVW9KaGhzCncrZXpJQmhyS3U2ZkxtQXF6RFFi
            aEJzU1NQWDhtekRaYXVHWVMzZ3VJa2sKLS0tIHlrL3puQWVwZUZKWDRXdlpleGFv
            ZzczQVBMbTZNaUJrLzV3dDBNenplSDgKFzque67A2D++pRqL0+DfdsrlDHruFAD0
            yv0K4RBBXBkA28LDvl2yhm3UL1uCxBATWjNEbNiTqG4af3S4FDX6RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142ekz45yqqhdn7e2vdwn2zw9e2qyz3fyq82ym9m8nzk6u5fnxejqd388ca
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T10:36:13Z"
    mac: ENC[AES256_GCM,data:XJOD6WZ3Q4p11q+lWEZPNg9TmMvrbdu1cG4FPdXd1t0OplHpoqpQk+JXUMgbYplP/nurTUzpTRANc/h4FSZep4XYvAIQ6QxWYXA8jams5kSCuypDmr7PDfSZrX5tyTxLs7MJTId++NTK+2V5sTQX90s8a09vNDDh+kuDwaEV80c=,iv:yC6DQHHKITZK7Ya6o6931erxuIVw7y10nQfJKD1TMig=,tag:/4exU8IObAekKl/ryGMHOQ==,type:str]
    version: 3.13.3
