apiVersion: v1
data:
    password: ENC[AES256_GCM,data:DVP39lacBrXW3O1rUGEGv5A6AKuE1QTwha6qkB1dFXW2nf2Wq0lP8Ov9yOBBWAqMiSW+WUlNS113xk6LX5xzuGZ4oFKFTQBvOlsTszCaHIt+hVRWCCn16Q==,iv:BlBSEwy4EJLRGtnrcds7ABIIyOP2nVlmyB4HGkrwJls=,tag:kEvEDEqv/i0ToWjw6PqaEA==,type:str]
kind: Secret
metadata:
    name: redis-auth
    namespace: takovibe
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOFl3bVZ2L1J4dG5TOHRV
            Z01vL2o4YTN2eXU5TXlTYXdOMkVKdlpHdVRnCkppcFF2NDdLWXc3UllOUXRqbFp1
            c09hdDdib0FFbTNQOG80THQzRjZGLzgKLS0tIHFobU9jOC83T3l3SGxSZEJoZnNz
            cFVFMk8yR2NoaWlxOW1lL1lrQ25Gb0EKW2/AA9dtLA93wnLMtf7tqWSC90Iwq7kf
            rvsjwvpWO+nHGPOH8gPqTSQjHl51WoDpwAemdION/6jmTKRRTLV4Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142ekz45yqqhdn7e2vdwn2zw9e2qyz3fyq82ym9m8nzk6u5fnxejqd388ca
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T10:36:13Z"
    mac: ENC[AES256_GCM,data:NcX/aG+DSmiyGHNqeXzdwh6PcC2aTnOYaMVJP+IvU8O5rf96FeguekBqWShpFmLXzakO5ZnPHq7THdKExNxZc5bMqxoR3GIDYiHdolAo8+HPYKOPdtgg1aHzXXYw8mIDZotuPxWmvLdhc9UUZKbeDy5urGr2O2C+KeTc1xfcrLU=,iv:hnschceeSONVurLrWXcUOCWihiJ/6DG5hS3SwMHhyM0=,tag:n4VYBAhYDYv5MxxcvlhW9w==,type:str]
    version: 3.13.3
